### ISSUE TITLE
Exception thrown while graphviz rendering

### ISSUE THREAD

**Issue by SimonIT** [nidi3/graphviz-java#130]
Hello,

I'm trying to make a tree with random strings. For this, I'm using [this](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/RandomStringUtils.html#random-int-) Method to generate the strings and make nodes with `node(randomString)`.  When I try to render the graphviz with `graphviz.render(Format.SVG).toImage()`, I'm getting this exception:
```java
[Fatal Error] :476:17: Ungültiges XML-Zeichen (Unicode: 0x17) wurde im Kommentar gefunden.
Okt. 28, 2019 4:54:14 NACHM. com.kitfox.svg.SVGUniverse loadSVG
WARNUNG: Error processing svgSalamander://graph/
org.xml.sax.SAXParseException; lineNumber: 476; columnNumber: 17; Ungültiges XML-Zeichen (Unicode: 0x17) wurde im Kommentar gefunden.
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1243)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at com.kitfox.svg.SVGUniverse.loadSVG(SVGUniverse.java:608)
	at com.kitfox.svg.SVGUniverse.loadSVG(SVGUniverse.java:545)
	at com.kitfox.svg.SVGUniverse.loadSVG(SVGUniverse.java:502)
	at guru.nidi.graphviz.engine.SalamanderRasterizer.createDiagram(SalamanderRasterizer.java:60)
	at guru.nidi.graphviz.engine.SalamanderRasterizer.doRasterize(SalamanderRasterizer.java:32)
	at guru.nidi.graphviz.engine.SvgRasterizer.rasterize(SvgRasterizer.java:35)
	at guru.nidi.graphviz.engine.Renderer.toImage(Renderer.java:117)
	at guru.nidi.graphviz.engine.EngineResult.map(EngineResult.java:58)
	at guru.nidi.graphviz.engine.Renderer.toImage(Renderer.java:109)
	at guru.nidi.graphviz.engine.Renderer.toImage(Renderer.java:105)
	at de.szut.simNil.binaryMaple.gui.TreeVisualizer.getGraphvizImage(TreeVisualizer.java:187)
	at de.szut.simNil.binaryMaple.gui.AbstractController.lambda$updateGraphvizImage$10(AbstractController.java:232)
	at java.base/java.lang.Thread.run(Thread.java:834)
[WARNING] 
java.lang.NullPointerException
    at guru.nidi.graphviz.engine.SalamanderRasterizer.createDiagram (SalamanderRasterizer.java:62)
    at guru.nidi.graphviz.engine.SalamanderRasterizer.doRasterize (SalamanderRasterizer.java:32)
    at guru.nidi.graphviz.engine.SvgRasterizer.rasterize (SvgRasterizer.java:35)
    at guru.nidi.graphviz.engine.Renderer.toImage (Renderer.java:117)
    at guru.nidi.graphviz.engine.EngineResult.map (EngineResult.java:58)
    at guru.nidi.graphviz.engine.Renderer.toImage (Renderer.java:109)
    at guru.nidi.graphviz.engine.Renderer.toImage (Renderer.java:105)
    at de.szut.simNil.binaryMaple.gui.TreeVisualizer.getGraphvizImage (TreeVisualizer.java:187)
    at de.szut.simNil.binaryMaple.gui.AbstractController.lambda$updateGraphvizImage$10 (AbstractController.java:232)
    at java.lang.Thread.run (Thread.java:834)
```
It does also not work with the `randomAscii` Method. With this, I get for example this exception:
```java
[WARNING] 
guru.nidi.graphviz.engine.GraphvizException: Error: syntax error in line 1 near '('

    at guru.nidi.graphviz.engine.ResultHandler.waitFor (ResultHandler.java:42)
    at guru.nidi.graphviz.engine.GraphvizV8Engine$Env.execute (GraphvizV8Engine.java:99)
    at guru.nidi.graphviz.engine.GraphvizV8Engine.jsExecute (GraphvizV8Engine.java:68)
    at guru.nidi.graphviz.engine.AbstractJsGraphvizEngine.execute (AbstractJsGraphvizEngine.java:38)
    at guru.nidi.graphviz.engine.Graphviz.execute (Graphviz.java:211)
    at guru.nidi.graphviz.engine.Renderer.execute (Renderer.java:133)
    at guru.nidi.graphviz.engine.Renderer.toImage (Renderer.java:105)
    at de.szut.simNil.binaryMaple.gui.TreeVisualizer.getGraphvizImage (TreeVisualizer.java:187)
    at de.szut.simNil.binaryMaple.gui.AbstractController.lambda$updateGraphvizImage$10 (AbstractController.java:232)
    at java.lang.Thread.run (Thread.java:834)
```

**Comment by mx1up** [comment]
1) I would give batik rasterizer a try instead of salamander
2) try different engine, for example, the CLI engine
see the sample code on the front page

**Comment by SimonIT** [comment]
Batik rasterizer seem to work. But in my opinion, all should work

**Comment by mx1up** [comment]
yes, of course, but now we know it is a svg salamander bug :) I suggest filing an issue there : https://github.com/blackears/svgSalamander

**Comment by blackears** [comment]
Hi.  I maintain SVG Salamander and got a message about this from user SimonIT.  I requested a sample of the SVG that was causing this error, but he says that the graphviz tool does this all under the hood and he does not know what the SVG was.  Would someone be able to provide me with a sample of the SVG that is causing the error?

**Comment by nidi3** [comment]
I don't think it's a salamander issue, but a problem of correct string escaping (java -> javascript -> svg)

**Comment by nidi3** [comment]
I improved the escpaing in version `0.11.1`, but it's tricky and maybe still not perfect.

**Comment by SimonIT** [comment]
I'm still getting this exception:
```
[WARNING] 
guru.nidi.graphviz.engine.GraphvizException: Error: syntax error in line 1 near '('

    at guru.nidi.graphviz.engine.ResultHandler.waitFor (ResultHandler.java:42)
    at guru.nidi.graphviz.engine.GraphvizV8Engine$Env.execute (GraphvizV8Engine.java:99)
    at guru.nidi.graphviz.engine.GraphvizV8Engine.jsExecute (GraphvizV8Engine.java:68)
    at guru.nidi.graphviz.engine.AbstractJsGraphvizEngine.execute (AbstractJsGraphvizEngine.java:38)
    at guru.nidi.graphviz.engine.Graphviz.execute (Graphviz.java:202)
    at guru.nidi.graphviz.engine.Renderer.execute (Renderer.java:133)
    at guru.nidi.graphviz.engine.Renderer.toImage (Renderer.java:105)
    at de.szut.simNil.binaryMaple.gui.TreeVisualizer.getGraphvizImage (TreeVisualizer.java:228)
    at de.szut.simNil.binaryMaple.gui.AbstractController.lambda$updateGraphvizImage$11 (AbstractController.java:295)
    at java.lang.Thread.run (Thread.java:834)
```

**Comment by nidi3** [comment]
is it with `random` or `randomAscii`? 
Could you attach here the graph`Graphviz.fromGraph(g).render(DOT).toFile(new File(...);`

**Comment by nidi3** [comment]
Also you get always the same error? Sounds not very like random... maybe there's another cause for the problem?

**Comment by SimonIT** [comment]
That's a graph with `random`:
```
graph {
graph ["bgcolor"="#00000000"]
"氙ᤎﱠ太䟌䷒" ["style"="filled,setlinewidth(2)","fillcolor"="white","fontcolor"="black","color"="green"]
"嫋᭲옝寉㼄" ["style"="filled,setlinewidth(2)","fillcolor"="white","fontcolor"="black"]
"遛𫱼ᮩ唿" ["style"="filled,setlinewidth(2)","fillcolor"="white","fontcolor"="black"]
"𝠿뛑𬷑" ["style"="filled,setlinewidth(2)","fillcolor"="white","fontcolor"="black","color"="green"]
"슇𡺹솧숹" ["style"="filled,setlinewidth(2)","fillcolor"="white","fontcolor"="black"]
"𢞭ͦ脱珄?\n?" ["style"="filled,setlinewidth(2)","fillcolor"="white","fontcolor"="black","color"="green"]
"𠦍𪑼肗" ["style"="filled,setlinewidth(2)","fillcolor"="white","fontcolor"="black"]
"ﾃ䄪𝠛𣅧\n伣" ["style"="filled,setlinewidth(2)","fillcolor"="white","fontcolor"="black","color"="green"]
"𨼤𨩢㴓" ["style"="filled,setlinewidth(2)","fillcolor"="white","fontcolor"="black"]
"㒒𨿽奛讙" ["style"="filled,setlinewidth(2)","fillcolor"="brown","fontcolor"="white","color"="brown"]
"嫋᭲옝寉㼄" -- "氙ᤎﱠ太䟌䷒"
"遛𫱼ᮩ唿" -- "嫋᭲옝寉㼄"
"슇𡺹솧숹" -- "遛𫱼ᮩ唿"
"슇𡺹솧숹" -- "𝠿뛑𬷑"
"𠦍𪑼肗" -- "슇𡺹솧숹"
"𠦍𪑼肗" -- "𢞭ͦ脱珄?\n?"
"𨼤𨩢㴓" -- "𠦍𪑼肗"
"𨼤𨩢㴓" -- "ﾃ䄪𝠛𣅧\n伣"
"㒒𨿽奛讙" -- "𨼤𨩢㴓"
}
```

And that's one with `randomAscii`:
```
graph {
graph ["bgcolor"="#00000000"]
"3" ["style"="filled,setlinewidth(2)","fillcolor"="white","fontcolor"="black","color"="green"]
"3|^H" ["style"="filled,setlinewidth(2)","fillcolor"="white","fontcolor"="black"]
">" ["style"="filled,setlinewidth(2)","fillcolor"="white","fontcolor"="black"]
"O%LN" ["style"="filled,setlinewidth(2)","fillcolor"="white","fontcolor"="black","color"="green"]
"KF" ["style"="filled,setlinewidth(2)","fillcolor"="white","fontcolor"="black"]
"K" ["style"="filled,setlinewidth(2)","fillcolor"="white","fontcolor"="black"]
"PAI" ["style"="filled,setlinewidth(2)","fillcolor"="white","fontcolor"="black","color"="green"]
"c0oY" ["style"="filled,setlinewidth(2)","fillcolor"="white","fontcolor"="black","color"="green"]
"^3\" ["style"="filled,setlinewidth(2)","fillcolor"="white","fontcolor"="black"]
"iX" ["style"="filled,setlinewidth(2)","fillcolor"="white","fontcolor"="black","color"="green"]
"o>" ["style"="filled,setlinewidth(2)","fillcolor"="white","fontcolor"="black"]
"r" ["style"="filled,setlinewidth(2)","fillcolor"="white","fontcolor"="black"]
"fPjk" ["style"="filled,setlinewidth(2)","fillcolor"="white","fontcolor"="black"]
"Vme" ["style"="filled,setlinewidth(2)","fillcolor"="white","fontcolor"="black"]
"O~" ["style"="filled,setlinewidth(2)","fillcolor"="white","fontcolor"="black"]
"xL=#" ["style"="filled,setlinewidth(2)","fillcolor"="white","fontcolor"="black","color"="green"]
"~5<'" ["style"="filled,setlinewidth(2)","fillcolor"="white","fontcolor"="black","color"="green"]
"{@z" ["style"="filled,setlinewidth(2)","fillcolor"="white","fontcolor"="black"]
"z" ["style"="filled,setlinewidth(2)","fillcolor"="white","fontcolor"="black"]
"uT6X" ["style"="filled,setlinewidth(2)","fillcolor"="brown","fontcolor"="white","color"="brown"]
"3|^H" -- "3"
">" -- "3|^H"
"KF" -- "O%LN"
"K" -- ">"
"K" -- "KF"
"^3\" -- "c0oY"
"o>" -- "iX"
"r" -- "o>"
"fPjk" -- "^3\"
"fPjk" -- "r"
"Vme" -- "PAI"
"Vme" -- "fPjk"
"O~" -- "K"
"O~" -- "Vme"
"{@z" -- "~5<'"
"z" -- "xL=#"
"z" -- "{@z"
"uT6X" -- "O~"
"uT6X" -- "z"
}
```
In both cases appears the exception
It's always this:
```
[WARNING] 
guru.nidi.graphviz.engine.GraphvizException: Error: syntax error in line 1 near '('

    at guru.nidi.graphviz.engine.ResultHandler.waitFor (ResultHandler.java:42)
    at guru.nidi.graphviz.engine.GraphvizV8Engine$Env.execute (GraphvizV8Engine.java:99)
    at guru.nidi.graphviz.engine.GraphvizV8Engine.jsExecute (GraphvizV8Engine.java:68)
    at guru.nidi.graphviz.engine.AbstractJsGraphvizEngine.execute (AbstractJsGraphvizEngine.java:38)
    at guru.nidi.graphviz.engine.Graphviz.execute (Graphviz.java:202)
    at guru.nidi.graphviz.engine.Renderer.execute (Renderer.java:133)
    at guru.nidi.graphviz.engine.Renderer.toImage (Renderer.java:105)
    at de.szut.simNil.binaryMaple.gui.TreeVisualizer.getGraphvizImage (TreeVisualizer.java:228)
    at de.szut.simNil.binaryMaple.gui.AbstractController.lambda$updateGraphvizImage$11 (AbstractController.java:295)
    at java.lang.Thread.run (Thread.java:834)
```

**Comment by SimonIT** [comment]
That's the project: https://github.com/SimonIT/binaryMaple
I'm only changing `getRandomValue` in the `StringController`

**Comment by nidi3** [comment]
Thanks, I can reproduce it. Analyzing...

**Comment by nidi3** [comment]
In the second example, the problem is `"^3\" -- "c0oY"`: the backslash escapes the " and so the string ends only after the next ". This is fixed now.
The example with `random` works on my machine...

**Comment by nidi3** [comment]
Can you try it again with version `0.11.2`? 
(And `Format.fileExtension` is public now ;)

**Comment by SimonIT** [comment]
The problem still occurs here:
[tree.txt](https://github.com/nidi3/graphviz-java/files/3839863/tree.txt)

**Comment by nidi3** [comment]
Works on my machine, but I think when exporting the dot file, some characters are lost (all the ?).
How exactly did you generate this?

**Comment by nidi3** [comment]
Mybe the last byte of one of the unicode characters corresponds with a \ and causes the same issues as with `randomAscii`. Will try to reproduce this case.

**Comment by SimonIT** [comment]
It's basically `node(RandomStringUtils.random(10))` with some styling. I created a Branch https://github.com/SimonIT/binaryMaple/tree/random

**Comment by nidi3** [comment]
Found the problem. It's not in `random` but it's the newlines you add to the strings.
When using the complete set of unicode characters, `length` and `substring` cannot be used. Everything has to be based on code points. 
I created a pull request for it.

**Comment by SimonIT** [comment]
Thank you very much! And again something new I learned
